#!/bin/bash

# Move old configuration to /etc/self-service-password
for file in $( find /etc/self-service-password -name "*.save" -type f );
do
    # move previously created *.save file into its equivalent without .save
    mv ${file} ${file%.save}
done

# Clean cache
rm -rf /var/cache/self-service-password/{cache,templates_c}/*

# Change ownership of cache directories
chown www-data:www-data /var/cache/self-service-password/cache
chown www-data:www-data /var/cache/self-service-password/templates_c
