# PHP files
../conf/*      etc/self-service-password/
../htdocs/*    usr/share/self-service-password/htdocs/
../lang/*      usr/share/self-service-password/lang/
../lib/*       usr/share/self-service-password/lib/
../scripts/*   usr/share/self-service-password/scripts/
../templates/* usr/share/self-service-password/templates/
../vendor/*    usr/share/self-service-password/vendor/

# Apache configuration
debian/conf/* etc/apache2/sites-available/
