#!/bin/sh

set -e

# enable self-service-password for apache
if [ -x "`which a2ensite`" ]; then
  a2ensite self-service-password
fi

if [ -x "`which a2ensite`" ]; then
  a2ensite self-service-password-ssl
fi
echo "####################################################"
echo "To activate self-service-password you have to change"
echo "example.com to your corresponding domain name in"
echo "/etc/init.d/apache2/sites-enabled"
echo "####################################################"
echo "####################################################"
echo "You can also protect self-service-passwird via SSL"
echo "Just insert your certificate into self-service-password-ssl"
echo "####################################################"
exit 0
