# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See http://symfony.com/doc/current/cookbook/templating/render_without_controller.html
homepage:
    path: /
    defaults:
        _controller: default.controller:indexAction

change-password:
    path: /change-password
    defaults:
        _controller: change_password.controller:indexAction

change-security-question:
    path: /change-security-question
    defaults:
        _controller: change_security_questions.controller:indexAction

change-ssh-key:
    path: /change-ssh-key
    defaults:
        _controller: change_ssh_key.controller:indexAction

reset-password-by-question:
    path: /reset-password-by-question
    defaults:
        _controller: reset_password_by_question.controller:indexAction

reset-password-by-email:
    path: /reset-password-by-email
    defaults:
        _controller: get_token_by_email_verification.controller:indexAction

reset-password-by-sms:
    path: /reset-password-by-sms
    defaults:
        _controller: get_token_by_sms_verification.controller:indexAction

reset-password-with-token:
    path: /reset-password-with-token
    defaults:
        _controller: reset_password_by_token.controller:indexAction