#!/usr/bin/env bash

set -ex

INSTALL_PATHS=${INSTALL_PATHS:-" \
    htdocs/ \
    lang/ \
    lib/ \
    scripts/ \
    templates/ \
    vendor/ \
    LICENCE \
"}

EXCLUDE_PATHS=${EXCLUDE_PATHS:-" \
    htdocs/vendor/.gitignore \
"}

composer update --no-dev

INSTALL_EXPR=

for p in ${INSTALL_PATHS}; do \
    [ -z "${p##*/}" ] && p="\"./${p}*\"" || p="\"./$p\""
    INSTALL_EXPR="${INSTALL_EXPR:+${INSTALL_EXPR} -or }-path $p"
done

EXCLUDE_EXPR=
for p in ${EXCLUDE_PATHS}; do \
    [ -z "${p##*/}" ] && p="\"./${p}*\"" || p="\"./$p\""
    EXCLUDE_EXPR="${EXCLUDE_EXPR:+${EXCLUDE_EXPR} -or }-path $p"
done

BIN_PATHS=$(eval "find -type d -name bin \( $INSTALL_EXPR \) -not \( $EXCLUDE_EXPR \)")
BIN_EXPR=

for p in ${BIN_PATHS}; do \
    BIN_EXPR="${BIN_EXPR:+${BIN_EXPR} -or }-path \"$p/*\""
done

eval "find -type f \( $BIN_EXPR \) -exec install -p -m 755 --owner www-data --group www-data -D {} /rootfs/var/www/{} \;"

eval "find -type f \( $INSTALL_EXPR \) \
    -not \( $EXCLUDE_EXPR \) \
    -not \( $BIN_EXPR \) \
    -exec install -p -m 644 --owner www-data --group www-data -D {} /rootfs/var/www/{} \;"

chmod a+x /rootfs/var/www/scripts/*
install -m 755 packaging/docker/entrypoint.sh /rootfs/
install --owner www-data --group www-data --directory -D \
    "/rootfs/var/www/htdocs/vendor" "/rootfs/var/www/conf" "/rootfs/var/www/templates_c"

sed conf/config.inc.php \
    -e "s#/usr/share/php/smarty3#${SMARTY_DIR:-/usr/share/php/smarty3}#g" \
    -e "s#config\.inc\.local\.php#conf/\0#g" \
        > /rootfs/var/www/config.inc.php.orig

chown www-data:www-data /rootfs/var/www/config.inc.php.orig
